# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_reg_no', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students_profile_pictures/%Y/%m/d%')),
                ('supervisor_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_number', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200, null=True)),
                ('proposed_supervisor', models.CharField(max_length=200)),
            ],
        ),
    ]
