# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_member_reg_no', models.CharField(max_length=100)),
                ('second_member_reg_no', models.CharField(max_length=100)),
                ('third_member_reg_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='group_number',
            field=models.IntegerField(default=0, verbose_name=students.models.StudentGroups),
        ),
    ]
