# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20171016_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, verbose_name=students.models.Student)),
                ('message_from_supervisor', models.TextField(blank=True, null=True)),
                ('message_from_coordinator', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleProjects',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.Student')),
                ('semister1_progress', models.FileField(blank=True, null=True, upload_to='Student_SingleProject_Semister1_Progress/%Y/%m/%d')),
                ('semister1_final', models.FileField(blank=True, null=True, upload_to='Student_SingleProject_Semister1_Final/%Y/%m/%d')),
                ('semister2_progress', models.FileField(blank=True, null=True, upload_to='Student_SingleProject_Semister2_Progress/%Y/%m/%d')),
                ('semister2_Final', models.FileField(blank=True, null=True, upload_to='Student_SingleProject_Semister2_Final/%Y/%m/%d')),
                ('title', models.TextField(null=True)),
                ('concept_note', models.FileField(blank=True, null=True, upload_to='Students_Single_projects_ConceptNotes/%Y/%m/%d')),
                ('semister1_progress_grades', models.IntegerField(default=0)),
                ('semister1_final_grades', models.IntegerField(default=0)),
                ('semister2_progress_grades', models.IntegerField(default=0)),
                ('semister2_Final_grades', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentGroupProjects',
            new_name='GroupsProjects',
        ),
    ]
