# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20171016_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupsProjects',
            new_name='GroupsProject',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='SingleProjects',
            new_name='SingleProject',
        ),
    ]
