# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20171016_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleproject',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='SingleProject',
        ),
    ]
