# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='student_id',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
