# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20171016_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='bsc in comp science', max_length=100),
        ),
    ]
