# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20171016_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroups',
            name='id',
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='group_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
