# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20171016_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_number',
            field=models.IntegerField(default=0, verbose_name=students.models.StudentGroups),
        ),
    ]
