# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20171016_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_number',
            field=models.IntegerField(default=0),
        ),
    ]
