# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20171016_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
