# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20171016_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_reg_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
