# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20171017_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_number',
        ),
        migrations.AddField(
            model_name='student',
            name='studentgroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.StudentGroups'),
        ),
    ]
