# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20171017_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsproject',
            name='group_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='group_title', serialize=False, to='students.StudentGroups'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentgroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='student_set', to='students.StudentGroups'),
        ),
    ]
