# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20171018_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentgroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stud', to='students.StudentGroups'),
        ),
    ]
