# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_auto_20171018_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsproject',
            name='group_id',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='group_title', serialize=False, to='students.StudentGroups'),
        ),
    ]
