# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_auto_20171018_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.StudentGroups'),
        ),
    ]
