# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='proposed_supervisor',
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='proposed_supervisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
