# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_auto_20171028_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='supervisor_employee_id',
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='supervisor_employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
