# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_auto_20171103_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroups',
            name='second_member_reg_no',
            field=models.CharField(default='null', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='third_member_reg_no',
            field=models.CharField(default='null', max_length=100, null=True, unique=True),
        ),
    ]
