# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_auto_20171103_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='students.StudentGroups'),
        ),
    ]
