# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_auto_20171108_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='student_id',
        ),
        migrations.AddField(
            model_name='message',
            name='student_group_id',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.StudentGroups'),
        ),
    ]
