# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_auto_20171119_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='student_group_id',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.StudentGroups'),
        ),
    ]
