# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0051_auto_20171119_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='creted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
