# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_message_creted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_from_coordinator',
        ),
    ]
