# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0053_remove_message_message_from_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFromCoordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from_cordinator', models.TextField(blank=True, null=True)),
                ('creted_at', models.DateTimeField(auto_now_add=True)),
                ('student_group_id', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.StudentGroups')),
            ],
        ),
    ]
