# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
