# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_tables', '0002_pastprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysteamControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitConceptNote', models.BooleanField(default=True)),
            ],
        ),
    ]
