# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:06
from __future__ import unicode_literals

import coordinator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_auto_20171016_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorAnaucements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_employee_id', models.CharField(max_length=100, verbose_name=coordinator.models.Coordinator)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
