# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_coordinator_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatoranaucements',
            name='creted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
