# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_coordinatoranaucements_creted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatoranaucements',
            name='coordinator_employee_id',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='coordinator.Coordinator'),
        ),
    ]
