# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0007_auto_20171016_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='role',
            field=models.CharField(default='cordinaor', max_length=20),
        ),
    ]
