# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import supervisor.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('supervisor_employee_id', models.CharField(max_length=100, verbose_name=supervisor.models.Supervisor)),
                ('recomandation', models.CharField(default='waiting', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSingleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_single_project_id', models.IntegerField()),
                ('supervisor_employee_id', models.CharField(max_length=100, verbose_name=supervisor.models.Supervisor)),
            ],
        ),
        migrations.CreateModel(
            name='SudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('supervisor_employee_id', models.CharField(max_length=100, verbose_name=supervisor.models.Supervisor)),
            ],
        ),
    ]
