# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_receivedconcepts_studentsinglegroup_sudentgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceivedConcepts',
            new_name='ReceivedConcept',
        ),
    ]
