# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0005_auto_20171016_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageFromSudents',
        ),
    ]
