# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0006_auto_20171019_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='role',
            field=models.CharField(default='supervisor', max_length=20),
        ),
    ]
