# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0007_supervisor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedconcept',
            name='id',
        ),
        migrations.AlterField(
            model_name='receivedconcept',
            name='group_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
