# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0011_messagefromsudents_creted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefromsudents',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
