# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0012_messagefromsudents_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefromsudents',
            name='creted_at',
        ),
    ]
