# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0014_messagefromsudents_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_supervisor', models.CharField(max_length=100)),
                ('second_supervisor', models.CharField(max_length=100)),
                ('third_supervisor', models.CharField(max_length=100)),
                ('fourth_supervisor', models.CharField(max_length=100)),
                ('fifth_supervisor', models.CharField(max_length=100)),
                ('six_supervisor', models.CharField(max_length=100)),
                ('seven_supervisor', models.CharField(max_length=100)),
                ('eight_supervisor', models.CharField(max_length=100)),
                ('first_groupid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
