# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0016_auto_20180109_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='id',
        ),
        migrations.AddField(
            model_name='panel',
            name='panel_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
